
# Source a global bashrc
# if one exists
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi


#
# GLOBAL SOURCES
# (GENERIC FOR ALL LINUX SYSTEMS)
#

# PS 1 Prompt
export PS1="\w: "
export PATH="/usr/local/bin:/usr/local/sbin:$PATH" 

# Colors
export CLICOLOR=1
export LSCOLORS=exfxfxfxcxfxfxcxcxexex

# Aliases
alias make_tar="tar -cvzf"
alias untar="tar -zxvf"

# Python
export PYTHONSTARTUP=~/.pystartup

# Source a local bashrc
# if one exists
if [ -f ${HOME}/.bashrc_local ]; then
    source ${HOME}/.bashrc_local
fi

# All Done
